trading_hours:
  start: "08:50:00"
  end: "23:59:59"

plugins:
  - name: replay
    library: ../bin/libmod_replay.so
    enabled: true
    config:
      data_file: "../data/market_data_20260129"
      debug: false