trading_hours:
  start: "08:50:00"
  end: "15:30:00"

plugins:
  - name: CTP_Market
    library: "../bin/libmod_ctp.so"
    enabled: true
    config:
      symbol: rb2410
      front_addr: "tcp://180.168.146.187:10211"
      broker_id: "9999"
      account: "00001"

  - name: Grid_Strategy_A
    library: "../bin/libmod_strategy.so"
    enabled: true
    config:
      buy_thresh: 3480.0
      sell_thresh: 3520.0
      max_pos: 10

  - name: Simple_Trade
    library: "../bin/libmod_trade.so"
    enabled: true
    config:
      id: SimTrade_1
