trading_hours:
  start: "09:00:00"
  end: "23:00:00"

plugins:
  - name: Replay
    library: "../bin/libmod_replay.so"
    enabled: true
    config:
      data_file: "../data/market_data_20260129"

  - name: StrategyTree
    library: "../bin/libmod_strategy_tree.so"
    enabled: true
    config:
      nodes:
        - id: STAT_ARB_AU
          library: "../bin/libstrat_stat_arb.so"
          params:
            symbol: au2606
            window_size: 100
            sigma: 4.0
            debug: true

  - name: TradeSim
    library: "../bin/libmod_trade.so"
    enabled: true
    config: {}
