md_front: tcp://182.254.243.31:40011
broker_id: '9999'
user_id: ''
password: ''
symbols:
- AP603
- AP604
- AP605
- AP610
- AP611
- AP612
- AP701
- CF603
- CF605
- CF607
- CF609
- CF611
- CF701
- CJ603
- CJ605
- CJ607
- CJ609
- CJ612
- CJ701
- CY602
- CY603
- CY604
- CY605
- CY606
- CY607
- CY608
- CY609
- CY610
- CY611
- CY612
- CY701
- FG602
- FG603
- FG604
- FG605
- FG606
- FG607
- FG608
- FG609
- FG610
- FG611
- FG612
- FG701
- IC2602
- IC2603
- IC2606
- IC2609
- IF2602
- IF2603
- IF2606
- IF2609
- IH2602
- IH2603
- IH2606
- IH2609
- IM2602
- IM2603
- IM2606
- IM2609
- JR603
- JR605
- JR607
- JR609
- JR611
- JR701
- MA602
- MA603
- MA604
- MA605
- MA606
- MA607
- MA608
- MA609
- MA610
- MA611
- MA612
- MA701
- OI603
- OI605
- OI607
- OI609
- OI611
- OI701
- PF602
- PF603
- PF604
- PF605
- PF606
- PF607
- PF608
- PF609
- PF610
- PF611
- PF612
- PF701
- PK603
- PK604
- PK605
- PK610
- PK611
- PK612
- PK701
- PL602
- PL603
- PL604
- PL605
- PL606
- PL607
- PL608
- PL609
- PL610
- PL611
- PL612
- PL701
- PM603
- PM605
- PM607
- PM609
- PM611
- PM701
- PR602
- PR603
- PR604
- PR605
- PR606
- PR607
- PR608
- PR609
- PR610
- PR611
- PR612
- PR701
- PX602
- PX603
- PX604
- PX605
- PX606
- PX607
- PX608
- PX609
- PX610
- PX611
- PX612
- PX701
- RI603
- RI605
- RI607
- RI609
- RI611
- RI701
- RM603
- RM605
- RM607
- RM608
- RM609
- RM611
- RM701
- RS607
- RS608
- RS609
- RS611
- SA602
- SA603
- SA604
- SA605
- SA606
- SA607
- SA608
- SA609
- SA610
- SA611
- SA612
- SA701
- SF602
- SF603
- SF604
- SF605
- SF606
- SF607
- SF608
- SF609
- SF610
- SF611
- SF612
- SF701
- SH602
- SH603
- SH604
- SH605
- SH606
- SH607
- SH608
- SH609
- SH610
- SH611
- SH612
- SH701
- SM602
- SM603
- SM604
- SM605
- SM606
- SM607
- SM608
- SM609
- SM610
- SM611
- SM612
- SM701
- SR603
- SR605
- SR607
- SR609
- SR611
- SR701
- T2603
- T2606
- T2609
- TA602
- TA603
- TA604
- TA605
- TA606
- TA607
- TA608
- TA609
- TA610
- TA611
- TA612
- TA701
- TF2603
- TF2606
- TF2609
- TL2603
- TL2606
- TL2609
- TS2603
- TS2606
- TS2609
- UR602
- UR603
- UR604
- UR605
- UR606
- UR607
- UR608
- UR609
- UR610
- UR611
- UR612
- UR701
- WH603
- WH605
- WH607
- WH609
- WH611
- WH701
- ZC602
- ZC603
- ZC604
- ZC605
- ZC606
- ZC607
- ZC608
- ZC609
- ZC610
- ZC611
- ZC612
- ZC701
- a2603
- a2605
- a2607
- a2609
- a2611
- a2701
- ad2602
- ad2603
- ad2604
- ad2605
- ad2606
- ad2607
- ad2608
- ad2609
- ad2610
- ad2611
- ad2612
- ad2701
- ag2602
- ag2603
- ag2604
- ag2605
- ag2606
- ag2607
- ag2608
- ag2609
- ag2610
- ag2611
- ag2612
- ag2701
- al2602
- al2603
- al2604
- al2605
- al2606
- al2607
- al2608
- al2609
- al2610
- al2611
- al2612
- al2701
- ao2602
- ao2603
- ao2604
- ao2605
- ao2606
- ao2607
- ao2608
- ao2609
- ao2610
- ao2611
- ao2612
- ao2701
- au2602
- au2603
- au2604
- au2606
- au2608
- au2610
- au2612
- au2702
- b2602
- b2603
- b2604
- b2605
- b2606
- b2607
- b2608
- b2609
- b2610
- b2611
- b2612
- b2701
- bb2603
- bb2605
- bb2607
- bb2609
- bb2611
- bb2701
- bc2602
- bc2603
- bc2604
- bc2605
- bc2606
- bc2607
- bc2608
- bc2609
- bc2610
- bc2611
- bc2612
- bc2701
- br2602
- br2603
- br2604
- br2605
- br2606
- br2607
- br2608
- br2609
- br2610
- br2611
- br2612
- br2701
- bu2602
- bu2603
- bu2604
- bu2605
- bu2606
- bu2607
- bu2608
- bu2609
- bu2610
- bu2611
- bu2612
- bu2701
- bu2703
- bu2706
- bu2709
- bu2712
- bz2603
- bz2604
- bz2605
- bz2606
- bz2607
- bz2608
- bz2609
- bz2610
- bz2611
- bz2612
- bz2701
- c2603
- c2605
- c2607
- c2609
- c2611
- c2701
- cs2603
- cs2605
- cs2607
- cs2609
- cs2611
- cs2701
- cu2602
- cu2603
- cu2604
- cu2605
- cu2606
- cu2607
- cu2608
- cu2609
- cu2610
- cu2611
- cu2612
- cu2701
- eb2602
- eb2603
- eb2604
- eb2605
- eb2606
- eb2607
- eb2608
- eb2609
- eb2610
- eb2611
- eb2612
- eb2701
- ec2602
- ec2604
- ec2606
- ec2608
- ec2610
- ec2612
- eg2602
- eg2603
- eg2604
- eg2605
- eg2606
- eg2607
- eg2608
- eg2609
- eg2610
- eg2611
- eg2612
- eg2701
- fb2602
- fb2603
- fb2604
- fb2605
- fb2606
- fb2607
- fb2608
- fb2609
- fb2610
- fb2611
- fb2612
- fb2701
- fu2603
- fu2604
- fu2605
- fu2606
- fu2607
- fu2608
- fu2609
- fu2610
- fu2611
- fu2612
- fu2701
- fu2702
- hc2602
- hc2603
- hc2604
- hc2605
- hc2606
- hc2607
- hc2608
- hc2609
- hc2610
- hc2611
- hc2612
- hc2701
- i2602
- i2603
- i2604
- i2605
- i2606
- i2607
- i2608
- i2609
- i2610
- i2611
- i2612
- i2701
- j2602
- j2603
- j2604
- j2605
- j2606
- j2607
- j2608
- j2609
- j2610
- j2611
- j2612
- j2701
- jd2602
- jd2603
- jd2604
- jd2605
- jd2606
- jd2607
- jd2608
- jd2609
- jd2610
- jd2611
- jd2612
- jd2701
- jm2602
- jm2603
- jm2604
- jm2605
- jm2606
- jm2607
- jm2608
- jm2609
- jm2610
- jm2611
- jm2612
- jm2701
- l2602
- l2603
- l2603F
- l2604
- l2604F
- l2605
- l2605F
- l2606
- l2606F
- l2607
- l2607F
- l2608
- l2608F
- l2609
- l2610
- l2611
- l2612
- l2701
- lc2602
- lc2603
- lc2604
- lc2605
- lc2606
- lc2607
- lc2608
- lc2609
- lc2610
- lc2611
- lc2612
- lc2701
- lg2603
- lg2605
- lg2607
- lg2609
- lg2611
- lg2701
- lh2603
- lh2605
- lh2607
- lh2609
- lh2611
- lh2701
- lu2603
- lu2604
- lu2605
- lu2606
- lu2607
- lu2608
- lu2609
- lu2610
- lu2611
- lu2612
- lu2701
- lu2702
- m2603
- m2605
- m2607
- m2608
- m2609
- m2611
- m2612
- m2701
- ni2602
- ni2603
- ni2604
- ni2605
- ni2606
- ni2607
- ni2608
- ni2609
- ni2610
- ni2611
- ni2612
- ni2701
- nr2602
- nr2603
- nr2604
- nr2605
- nr2606
- nr2607
- nr2608
- nr2609
- nr2610
- nr2611
- nr2612
- nr2701
- op2602
- op2603
- op2604
- op2605
- op2606
- op2607
- op2608
- op2609
- op2610
- op2611
- op2612
- op2701
- p2602
- p2603
- p2604
- p2605
- p2606
- p2607
- p2608
- p2609
- p2610
- p2611
- p2612
- p2701
- pb2602
- pb2603
- pb2604
- pb2605
- pb2606
- pb2607
- pb2608
- pb2609
- pb2610
- pb2611
- pb2612
- pb2701
- pd2606
- pd2608
- pd2610
- pd2612
- pg2602
- pg2603
- pg2604
- pg2605
- pg2606
- pg2607
- pg2608
- pg2609
- pg2610
- pg2611
- pg2612
- pg2701
- pp2602
- pp2603
- pp2603F
- pp2604
- pp2604F
- pp2605
- pp2605F
- pp2606
- pp2606F
- pp2607
- pp2607F
- pp2608
- pp2608F
- pp2609
- pp2610
- pp2611
- pp2612
- pp2701
- ps2602
- ps2603
- ps2604
- ps2605
- ps2606
- ps2607
- ps2608
- ps2609
- ps2610
- ps2611
- ps2612
- ps2701
- pt2606
- pt2608
- pt2610
- pt2612
- rb2602
- rb2603
- rb2604
- rb2605
- rb2606
- rb2607
- rb2608
- rb2609
- rb2610
- rb2611
- rb2612
- rb2701
- rr2602
- rr2603
- rr2604
- rr2605
- rr2606
- rr2607
- rr2608
- rr2609
- rr2610
- rr2611
- rr2612
- rr2701
- ru2603
- ru2604
- ru2605
- ru2606
- ru2607
- ru2608
- ru2609
- ru2610
- ru2611
- ru2701
- sc2603
- sc2604
- sc2605
- sc2606
- sc2607
- sc2608
- sc2609
- sc2610
- sc2611
- sc2612
- sc2701
- sc2702
- sc2703
- sc2706
- sc2709
- sc2712
- sc2803
- sc2806
- sc2809
- sc2812
- si2602
- si2603
- si2604
- si2605
- si2606
- si2607
- si2608
- si2609
- si2610
- si2611
- si2612
- si2701
- sn2602
- sn2603
- sn2604
- sn2605
- sn2606
- sn2607
- sn2608
- sn2609
- sn2610
- sn2611
- sn2612
- sn2701
- sp2602
- sp2603
- sp2604
- sp2605
- sp2606
- sp2607
- sp2608
- sp2609
- sp2610
- sp2611
- sp2612
- sp2701
- ss2602
- ss2603
- ss2604
- ss2605
- ss2606
- ss2607
- ss2608
- ss2609
- ss2610
- ss2611
- ss2612
- ss2701
- v2602
- v2603
- v2603F
- v2604
- v2604F
- v2605
- v2605F
- v2606
- v2606F
- v2607
- v2607F
- v2608
- v2608F
- v2609
- v2610
- v2611
- v2612
- v2701
- wr2602
- wr2603
- wr2604
- wr2605
- wr2606
- wr2607
- wr2608
- wr2609
- wr2610
- wr2611
- wr2612
- wr2701
- y2603
- y2605
- y2607
- y2608
- y2609
- y2611
- y2612
- y2701
- zn2602
- zn2603
- zn2604
- zn2605
- zn2606
- zn2607
- zn2608
- zn2609
- zn2610
- zn2611
- zn2612
- zn2701
output_path: ../data/
trading_day: '20260131'
start_time: 08:50:00
end_time: 02:40:00
