md_front: "tcp://182.254.243.31:30011"
broker_id: "9999"
user_id: ""
password: ""
symbols:
  - rb2605
  - hc2605
  - cu2605
  - au2606
  - ag2606
output_path: "../data/"
trading_day: "20260130"
start_time: "08:50:00"
end_time: "02:40:00"
